FROM buildpack-deps:buster

RUN apt-get update && apt-get install -y --no-install-recommends \
                bison \
                flex \
                build-essentials \
                cmake \
                git \
    && rm -rf /var/lib/apt/lists/*

ENV PBC_VERSION 0.5.14

RUN set -ex \
        \
        && wget -O pbc.tar.gz "https://crypto.stanford.edu/pbc/files/pbc-$PBC_VERSION.tar.gz" \
        && mkdir -p /usr/src/pbc \
        && tar -xzC /usr/src/pbc --strip-components=1 -f pbc.tar.gz \
        && rm pbc.tar.gz \
	    \
	    && cd /usr/src/pbc \
        && ./configure \
        && make \
        && make install 

RUN set -ex \
        \
        && cd /usr/src \
        && git clone "https://github.com/guanzhi/GmSSL.git" \
        && cd GmSSL \
        && mkdir build \ 
        && cd build \ 
        && cmake .. \
        && make \
        && make install 

RUN set -ex \
        \
        && cd home \
        && git clone https://github.com/debatem1/pypbc \
        && apt-get update \
        && apt-get -y install vim \
            python3-pip \
        \
        && cd pypbc \
        && pip3 install . \
        && pip3 install pycryptodome \
        && pip3 install gmssl-python
